config/routes.rb
Centroconstrucao::Application.routes.draw do

  devise_for :customers

  root to: 'customers#index'
  devise_for :admins

  namespace :admin do
    resources :customers
    resources :products
  end

  match 'admin', to: 'admin#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :tel, :age, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :value
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminController
  
  before_filter :load_customer, only: [:edit, :show]

  def index
  	@customers = Customer.all
  end

  def new
  	@customer = Customer.new
  end

  def create 
  	@customer = Customer.new(params[:customer])
  	if @customer.save
  	  redirect_to admin_customers_path, notice: "Salvo com sucesso"
  	else
      render :new
  	end
  end

  def update
  	@customer = Customer.find(params[:id])
  	if @customer.update_attributes(params[:customer])
  		redirect_to admin_customer_path(@customer), notice: "#{@customer.name}, salvo com sucesso"
  	else
  		render :edit
  	end
  end

  private

  def load_customer
  	@customer = Customer.find(params[:id])
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create 

    @product = Product.new(params[:product])
    if @product.save
      redirect_to admin_products_path, notice: "Salvo com sucesso"
    else
      render :new
    end
  end

  def update
    @product = Customer.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to admin_products_path(@product), notice: "#{@product.name}, salvo com sucesso"
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to admin_products_path, notice: "O Produto foi deletado com sucesso"
    end
  end

  private

  def load_product
    @product = Product.find(params[:id])
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController


  def index
  	@products = Product.all
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/customers/_form.html.slim
= simple_form_for [:admin, @customer] do |f|
  = f.input :name
  = f.input :tel
  = f.input :email
  = f.input :password
  = f.submit

app/views/admin/customers/edit.html.slim
h2 Editando #{@customer.name}
= render 'form'

app/views/admin/customers/index.html.slim
- if notice
  p= notice

h2 Clientes:

p
  strong= link_to "Novo cliente", new_admin_customer_path, class: "btn btn-large btn-success"
table.table.table-bordered.table-striped
  tr
    th Nome do cliente
    th Telefone
    th Email
    th Opçoes
  - @customers.each do |customer|
    tr
      td= link_to customer.name, [:admin, customer]
      td= customer.tel
      td= customer.email
      td
        = link_to "Editar", edit_admin_customer_path(customer), class: "btn"
        = link_to "Deletar", admin_customer_path(customer), method: :delete, class: "btn btn-danger"

app/views/admin/customers/new.html.slim
h2 Novo cliente
= render 'form'

app/views/admin/customers/show.html.slim
= notice

h2= @customer.name
p= @customer.email
p= @customer.tel

p= link_to "editar", edit_admin_customer_path(@customer)

app/views/admin/index.html.slim
h2 Painel de controle

app/views/admin/products/_form.html.slim
= simple_form_for [:admin, @product] do |f|
  = f.input :name
  = f.input :value
  = f.submit

app/views/admin/products/edit.html.slim
h2 Editando #{@product.name}
= render 'form'

app/views/admin/products/index.html.slim
- if notice
  p= notice

h2 Products:

p
  strong= link_to "Novo produto", new_admin_product_path, class: "btn btn-primary"
table.table
  table.table.table-bordered.table-striped
    tr
      th Nome do produto
      th Valor
      th Custo
      th Venda
      th opções
    - @products.each do |product|
      tr
        td= link_to product.name, [:admin, product]
        td= product.value
        td
        td
        td
          = link_to "Editar", edit_admin_product_path(product), class: "btn"
          = link_to "Deletar", admin_product_path(product), method: :delete, class: "btn btn-danger" 
        

app/views/admin/products/new.html.slim
h2 Novo Produto
= render 'form'

app/views/admin/products/show.html.slim
= notice

h2= @product.name
p= @product.value

p= link_to "editar", edit_admin_product_path(@product)

app/views/customers/index.html.slim
h1= pluralize(@products.count, " produto ", " produtos")


h2= number_to_currency(1000)

app/views/layouts/admin.html.slim
doctype 5
html
  head
  title Centroconstrucao
  = stylesheet_link_tag    "application", "bootstrap", :media => "all" 
  = javascript_include_tag "application"
  = csrf_meta_tags
  body
    container
      nav.navbar
        nav.navbar-inner
          nav.pull-right
            ul.nav
              li= render '/shared/search'
              li= link_to image_tag("cash.png", :size => "20x20", :alt => "Sua Conta"), destroy_admin_session_path, title: 'Sua Conta', method: :delete   
              li= link_to image_tag("settings.png", :size => "20x20"),title: 'Configurações' 
              li= link_to image_tag("exit.png", :size => "20x20", :alt => "Exit"), destroy_admin_session_path, title: 'Logout', method: :delete             
    row.row-fluid
      row.span9
      row.span3
        row.pull-right
          small Hello, #{current_admin.name}
    row.row-fluid   
      row.span1
      row.span10
        #header
          h1 Administração
          p
        container
          nav.navbar
            navbar
              .navbar
                .navbar-inner
                  .container
                    = link_to admin_path, class: "btn btn-navbar", "data-toggle" => "collapse",  "data-target" => ".nav-collapse" do
                      span.icon-bar
                    ul.nav
                      li.dropdown
                        = link_to "Dropdown <b class='caret'></b>".html_safe, admin_path, class: "dropdown-toggle", "data-toggle" => "dropdown"
                        ul.dropdown-menu
                          li= link_to "Action"              
                
        #content= yield
        #footer
          small Centro da Construção 2013.

app/views/layouts/application.html.slim
doctype 5
html
  head
  title Centroconstrucao
  = stylesheet_link_tag    "application", "bootstrap", :media => "all" 
  = javascript_include_tag "application"
  = csrf_meta_tags
  body
    #header
      h1 Loja Virtual CDC
    container
      nav.navbar
        nav.navbar-inner
          a.brand Menu
          ul.nav
            li
              = link_to 'Home',root_path
            li  
              = link_to 'Compra'
            li  
              = link_to 'Credito'
            li  
              = link_to 'logout', destroy_customer_session_path, title: 'Logout', method: :delete
    #wrapper.clearfix
      #twocols
        #maincol=yield
        #rightcol
          h2 right Column
      #leftcol
        h2 Left Column
    #footer
      h2 Footer

  

app/views/layouts/devise.html.slim
doctype 5
html
  head
  title Centroconstrucao
  = stylesheet_link_tag    "application", :media => "all" 
  = javascript_include_tag "application"
  = csrf_meta_tags
  body= yield
  #footer
    small Centro da Construção 2013.

app/views/shared/_search.html.slim
nav.form-search
  = simple_form_for :search, url: admin_path do |f|
    = f.input :term, input_html: {class: "input-medium search-query"}, label: false
    = f.submit "Buscar", class: "btn"